//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roxority_ExportZen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("roxority_ExportZen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportActions.
        /// </summary>
        public static string @__MenuActionDefaultSchema {
            get {
                return ResourceManager.GetString("__MenuActionDefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/images/roxority_ExportZen/ewr052.gif.
        /// </summary>
        public static string @__MenuActionIcon {
            get {
                return ResourceManager.GetString("__MenuActionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/images/roxority_ExportZen/icon16.png.
        /// </summary>
        public static string @__MenuActionIconSmall {
            get {
                return ResourceManager.GetString("__MenuActionIconSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _AdminHelpTopics {
            get {
                return ResourceManager.GetString("_AdminHelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; 2008-2011 ROXORITY Ltd. All rights reserved..
        /// </summary>
        public static string _Copyright {
            get {
                return ResourceManager.GetString("_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite,Basic,Ultimate.
        /// </summary>
        public static string _Editions {
            get {
                return ResourceManager.GetString("_Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        public static string _hasjquery {
            get {
                return ResourceManager.GetString("_hasjquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intro,setup,itemref_ExportActions,scheduling_sharepoint_list_data_csv_exports,farm_site_config,release_notes,eula.
        /// </summary>
        public static string _HelpTopics {
            get {
                return ResourceManager.GetString("_HelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intro,setup,itemref_ExportActions,scheduling_sharepoint_list_data_csv_exports,farm_site_config.
        /// </summary>
        public static string _HomeHelpTopics {
            get {
                return ResourceManager.GetString("_HomeHelpTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncLock.
        /// </summary>
        public static string _MappingKey {
            get {
                return ResourceManager.GetString("_MappingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 4, 0, 0, 1, 0, 1, 0, 191, 110, 41, 34, 52, 162, 132, 114, 98, 89, 127, 99, 38, 32, 0, 75, 155, 165, 4, 215, 182, 237, 1, 70, 86, 242, 248, 67, 193, 185, 124, 162, 14, 91, 84, 52, 223, 228, 64, 235, 203, 153, 16, 252, 202, 159, 119, 225, 45, 154, 96, 202, 200, 198, 14, 65, 255, 205, 174, 233, 194, 127, 125, 236, 82, 96, 92, 128, 159, 147, 32, 57, 226, 124, 128, 20, 197, 229, 111, 156, 243, 191, 23, 35, 232, 6, 29, 0, 158, 254, 85, 36, 23, 253, 243, 195, 229, 119,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _ProductID {
            get {
                return ResourceManager.GetString("_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roxority_ExportZen.
        /// </summary>
        public static string _ProductName {
            get {
                return ResourceManager.GetString("_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportZen.
        /// </summary>
        public static string _ProductTitle {
            get {
                return ResourceManager.GetString("_ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideAction:[never|auto|always];MultiSep:string;NoDefaultInst:bool.
        /// </summary>
        public static string _Settings {
            get {
                return ResourceManager.GetString("_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool_ExportActions,Tool_SiteUsers,Tool_Localizer,Tool_Transfer.
        /// </summary>
        public static string _Tools {
            get {
                return ResourceManager.GetString("_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roxority_.
        /// </summary>
        public static string _WhiteLabel {
            get {
                return ResourceManager.GetString("_WhiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _WhiteLabelAddress {
            get {
                return ResourceManager.GetString("_WhiteLabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@roxority.com.
        /// </summary>
        public static string _WhiteLabelEmail {
            get {
                return ResourceManager.GetString("_WhiteLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROXORITY Ltd..
        /// </summary>
        public static string _WhiteLabelTitle {
            get {
                return ResourceManager.GetString("_WhiteLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://roxority.com/.
        /// </summary>
        public static string _WhiteLabelUrl {
            get {
                return ResourceManager.GetString("_WhiteLabelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact#down.
        /// </summary>
        public static string _WhiteLabelUrlContact {
            get {
                return ResourceManager.GetString("_WhiteLabelUrlContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteFeature:65a0b7a9-080a-4bf7-8fed-5dc9de3654a1.
        /// </summary>
        public static string _WssItems {
            get {
                return ResourceManager.GetString("_WssItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always (requires activated Site Collection feature).
        /// </summary>
        public static string CfgSettingChoice_HideAction_always {
            get {
                return ResourceManager.GetString("CfgSettingChoice_HideAction_always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only if CSV export actions exist (requires activated Site Collection feature).
        /// </summary>
        public static string CfgSettingChoice_HideAction_auto {
            get {
                return ResourceManager.GetString("CfgSettingChoice_HideAction_auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string CfgSettingChoice_HideAction_never {
            get {
                return ResourceManager.GetString("CfgSettingChoice_HideAction_never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string CfgSettingDef_MultiSep {
            get {
                return ResourceManager.GetString("CfgSettingDef_MultiSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, your ExportZen action commands co-exist together with the built-in, out-of-box &apos;Export to Excel&apos; command. If you intend to fully replace that functionality with ExportZen, you can set whether and when to show (2007) / enable (2010) the built-in, out-of-box &apos;Export to Excel&apos; command (affects both both the SharePoint 2007 List Actions tool-bar menu item and the ribbon button in the SharePoint 2010 &apos;Connect and Export&apos; section of the List Tools ribbon tab)..
        /// </summary>
        public static string CfgSettingDesc_HideAction {
            get {
                return ResourceManager.GetString("CfgSettingDesc_HideAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This specifies the text used to combine the export value representations of List Columns containing multiple values, such as multi-Choice and multi-Lookup Columns..
        /// </summary>
        public static string CfgSettingDesc_MultiSep {
            get {
                return ResourceManager.GetString("CfgSettingDesc_MultiSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide (2007) or disable (2010) SharePoint&apos;s out-of-box &quot;Export to Excel&quot; command.
        /// </summary>
        public static string CfgSettingTitle_HideAction {
            get {
                return ResourceManager.GetString("CfgSettingTitle_HideAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator for exported multi-valued Column data.
        /// </summary>
        public static string CfgSettingTitle_MultiSep {
            get {
                return ResourceManager.GetString("CfgSettingTitle_MultiSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server-side default encoding [ {0} ].
        /// </summary>
        public static string DefaultEncoding {
            get {
                return ResourceManager.GetString("DefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-User License Agreement (EULA).
        /// </summary>
        public static string HelpTopic_eula {
            get {
                return ResourceManager.GetString("HelpTopic_eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Settings.
        /// </summary>
        public static string HelpTopic_farm_site_config {
            get {
                return ResourceManager.GetString("HelpTopic_farm_site_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Data Exports for SharePoint Lists.
        /// </summary>
        public static string HelpTopic_intro {
            get {
                return ResourceManager.GetString("HelpTopic_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for Export Actions.
        /// </summary>
        public static string HelpTopic_itemref_ExportActions {
            get {
                return ResourceManager.GetString("HelpTopic_itemref_ExportActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string HelpTopic_release_notes {
            get {
                return ResourceManager.GetString("HelpTopic_release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Automatic Background Exports.
        /// </summary>
        public static string HelpTopic_scheduling_sharepoint_list_data_csv_exports {
            get {
                return ResourceManager.GetString("HelpTopic_scheduling_sharepoint_list_data_csv_exports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Installation.
        /// </summary>
        public static string HelpTopic_setup {
            get {
                return ResourceManager.GetString("HelpTopic_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User agent (browser) locale (potentially unreliable / inconsistent settings!).
        /// </summary>
        public static string LocaleBrowser {
            get {
                return ResourceManager.GetString("LocaleBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server-side &apos;current&apos; locale -- [ {0} ].
        /// </summary>
        public static string LocaleCurrent {
            get {
                return ResourceManager.GetString("LocaleCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server-side installation locale -- [ {0} ].
        /// </summary>
        public static string LocaleSystem {
            get {
                return ResourceManager.GetString("LocaleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account locale (&apos;My Settings / My Regional Settings&apos;).
        /// </summary>
        public static string LocaleUser {
            get {
                return ResourceManager.GetString("LocaleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site locale (&apos;Site Settings / Regional Settings&apos;) -- [ {0} ].
        /// </summary>
        public static string LocaleWeb {
            get {
                return ResourceManager.GetString("LocaleWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The List specified in the &apos;exportlist&apos; URL parameter could not be found..
        /// </summary>
        public static string Old_NoExportList {
            get {
                return ResourceManager.GetString("Old_NoExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FilterZen Basic license is required for the &apos;Respect Currently Applied Filters&apos; feature..
        /// </summary>
        public static string Old_NoFilterZenEnt {
            get {
                return ResourceManager.GetString("Old_NoFilterZenEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified CSV Export Action Definition &apos;{0}&apos; could not be found ({1} actions scanned) --- fully refresh the previous page, and/or review your ExportZen action definitions under Site Settings / ExportZen Studio / Export Actions. User: {2}, lang: [{3}]..
        /// </summary>
        public static string Old_NoRuleItem {
            get {
                return ResourceManager.GetString("Old_NoRuleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepend UTF-8 byte order mark.
        /// </summary>
        public static string PC_ExportActions_bom {
            get {
                return ResourceManager.GetString("PC_ExportActions_bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export columns.
        /// </summary>
        public static string PC_ExportActions_cols {
            get {
                return ResourceManager.GetString("PC_ExportActions_cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportZen menu item description.
        /// </summary>
        public static string PC_ExportActions_desc {
            get {
                return ResourceManager.GetString("PC_ExportActions_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export encoding.
        /// </summary>
        public static string PC_ExportActions_enc {
            get {
                return ResourceManager.GetString("PC_ExportActions_enc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use semicolons instead of commas.
        /// </summary>
        public static string PC_ExportActions_excel {
            get {
                return ResourceManager.GetString("PC_ExportActions_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect currently applied filters (FilterZen only).
        /// </summary>
        public static string PC_ExportActions_filter {
            get {
                return ResourceManager.GetString("PC_ExportActions_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export locale.
        /// </summary>
        public static string PC_ExportActions_loc {
            get {
                return ResourceManager.GetString("PC_ExportActions_loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude the header row with column names.
        /// </summary>
        public static string PC_ExportActions_nf {
            get {
                return ResourceManager.GetString("PC_ExportActions_nf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore paging in PeopleZen exports.
        /// </summary>
        public static string PC_ExportActions_nopg {
            get {
                return ResourceManager.GetString("PC_ExportActions_nopg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore quick-filter tabs in PeopleZen exports.
        /// </summary>
        public static string PC_ExportActions_notb {
            get {
                return ResourceManager.GetString("PC_ExportActions_notb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column value separator.
        /// </summary>
        public static string PC_ExportActions_sep {
            get {
                return ResourceManager.GetString("PC_ExportActions_sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        public static string PC_ExportActions_sep_c {
            get {
                return ResourceManager.GetString("PC_ExportActions_sep_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon.
        /// </summary>
        public static string PC_ExportActions_sep_s {
            get {
                return ResourceManager.GetString("PC_ExportActions_sep_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string PC_ExportActions_sep_t {
            get {
                return ResourceManager.GetString("PC_ExportActions_sep_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ExportZen menu item in the following Lists.
        /// </summary>
        public static string PC_ExportActions_show {
            get {
                return ResourceManager.GetString("PC_ExportActions_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportZen menu item caption.
        /// </summary>
        public static string PC_ExportActions_title {
            get {
                return ResourceManager.GetString("PC_ExportActions_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply UNIX-style escaping.
        /// </summary>
        public static string PC_ExportActions_unix {
            get {
                return ResourceManager.GetString("PC_ExportActions_unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all item version history in separate column.
        /// </summary>
        public static string PC_ExportActions_vhcol {
            get {
                return ResourceManager.GetString("PC_ExportActions_vhcol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export item version history in separate rows, one per version.
        /// </summary>
        public static string PC_ExportActions_vhrows {
            get {
                return ResourceManager.GetString("PC_ExportActions_vhrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current View.
        /// </summary>
        public static string PC_ExportActions_view {
            get {
                return ResourceManager.GetString("PC_ExportActions_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;ONLY&lt;/b&gt; tick this option if you selected the UTF-8 encoding above &lt;b&gt;AND&lt;/b&gt; your exported contents are not decoded correctly by the external software that needs to consume this export in production. Recommended for opening UTF-8 exports in Excel..
        /// </summary>
        public static string PD_ExportActions_bom {
            get {
                return ResourceManager.GetString("PD_ExportActions_bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the List Columns (one per line) to include in that order in output CSV data files generated by this export action. (To rename a Column in the exported CSV, enter the List Column name, followed by a colon (:) and the CSV column name.) Be sure those Columns will be available in the exported List, otherwise the CSV column will remain empty.&lt;br/&gt;&lt;br/&gt;If you clear this setting and keep it blank, the export will include &lt;b&gt;all&lt;/b&gt; available View Columns shown..
        /// </summary>
        public static string PD_ExportActions_cols {
            get {
                return ResourceManager.GetString("PD_ExportActions_cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the description for this CSV export action to be shown in the export menu item for the Lists specified above..
        /// </summary>
        public static string PD_ExportActions_desc {
            get {
                return ResourceManager.GetString("PD_ExportActions_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only if your exports contain international characters that don&apos;t look as expected in external software importing this export should you start experimenting with different export encodings. The Unicode / UTF encodings are the recommended choices to test before trying other encodings. Keep this set to Default &lt;b&gt;UNLESS&lt;/b&gt; your exported contents are not decoded correctly by external software that needs to consume this export in production..
        /// </summary>
        public static string PD_ExportActions_enc {
            get {
                return ResourceManager.GetString("PD_ExportActions_enc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not recommended unless you and your users intend to only ever open these CSV exports in Microsoft Office Excel &lt;b&gt;AND&lt;/b&gt; Excel displays all comma-separated column values in a single cell (some internationalized Excel versions do that, some don&apos;t)..
        /// </summary>
        public static string PD_ExportActions_excel {
            get {
                return ResourceManager.GetString("PD_ExportActions_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If ticked, this export action only ever exports items included in the filtering currently applied to the applicable List View (&lt;b&gt;only&lt;/b&gt; supports filters supplied by a currently connected &lt;a target=&quot;_blank&quot; href=&quot;http://roxority.com/filterzen/&quot;&gt;FilterZen Filter Web Part&lt;/a&gt;)..
        /// </summary>
        public static string PD_ExportActions_filter {
            get {
                return ResourceManager.GetString("PD_ExportActions_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting controls how numbers and dates are represented in this export. For example, dates may be stored in an US format (due to your SharePoint installation) but your export consumers may use a different-locale version of Excel (such as for example German), which would then mis-read and mis-represent factually-correct, but US-formatted date values. Keep the default choice to start with and experiment as needed if results do not meet expectations..
        /// </summary>
        public static string PD_ExportActions_loc {
            get {
                return ResourceManager.GetString("PD_ExportActions_loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, ExportZen exports always begin with a header row denoting all column names. Tick this check-box option to skip this header row in your exports and instead only include raw data records..
        /// </summary>
        public static string PD_ExportActions_nf {
            get {
                return ResourceManager.GetString("PD_ExportActions_nf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even if the PeopleZen Web Part to be exported is paged, if this check-box option is ticked then all user profiles belonging to the Web Part are exported, instead of just those included in the currently shown page..
        /// </summary>
        public static string PD_ExportActions_nopg {
            get {
                return ResourceManager.GetString("PD_ExportActions_nopg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even if the PeopleZen Web Part to be exported is tabbed, if this check-box option is ticked then all user profiles belonging to the Web Part are exported, instead of just those included in the currently shown tab..
        /// </summary>
        public static string PD_ExportActions_notb {
            get {
                return ResourceManager.GetString("PD_ExportActions_notb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to semicolon if your users intend to only ever open these CSV exports in Microsoft Office Excel &lt;b&gt;AND&lt;/b&gt; their Excel version displays all comma-separated column values in a single cell (some internationalized Excel versions do that, some don&apos;t)..
        /// </summary>
        public static string PD_ExportActions_sep {
            get {
                return ResourceManager.GetString("PD_ExportActions_sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommended default separator for most CSV-consuming apps.
        /// </summary>
        public static string PD_ExportActions_sep_c {
            get {
                return ResourceManager.GetString("PD_ExportActions_sep_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternative CSV format required by some international Excel versions.
        /// </summary>
        public static string PD_ExportActions_sep_s {
            get {
                return ResourceManager.GetString("PD_ExportActions_sep_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to some CSV-consuming apps actually require TSV (tab-separated values).
        /// </summary>
        public static string PD_ExportActions_sep_t {
            get {
                return ResourceManager.GetString("PD_ExportActions_sep_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select in which Lists this export action will be offered as a menu item to end users (in the SharePoint 2007 &quot;Actions&quot; toolbar menu and in the SharePoint 2010 &quot;Connect and Export&quot; ribbon group (both only if the &quot;ExportZen List Integration&quot; Site Collection feature is activated too and for List Views, only with their Toolbar Type property set to Full or Show, not Summary or None)..
        /// </summary>
        public static string PD_ExportActions_show {
            get {
                return ResourceManager.GetString("PD_ExportActions_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the caption for this CSV export action to be shown in the export menu item for the Lists specified above. (If you do not specify a caption, the above name for this export action will be used, or if blank, its internal ID.).
        /// </summary>
        public static string PD_ExportActions_title {
            get {
                return ResourceManager.GetString("PD_ExportActions_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If un-ticked, ExportZen generates CSV data files using escaping patterns (for critical characters such as commas, line-breaks and quotes) that software written for Windows or Office is more likely to read flawlessly. Tick this check box to generate CSV data files using UNIX-style escaping patterns instead (only recommended if you get errors while feeding your exported CSV data files to other, non-Office software)..
        /// </summary>
        public static string PD_ExportActions_unix {
            get {
                return ResourceManager.GetString("PD_ExportActions_unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: if you&apos;d like ExportZen to append an additional column recording all version history per item (only for the Columns specified above, in a simple plain-text format), specify your preferred name for this CSV column here. Leave blank to not append a version history column.&lt;br/&gt;&lt;br/&gt;Not applicable to &lt;a target=&quot;_blank&quot; href=&quot;http://SharePoint-Tools.net/PeopleZen/&quot;&gt;User Profile exports via PeopleZen&lt;/a&gt;..
        /// </summary>
        public static string PD_ExportActions_vhcol {
            get {
                return ResourceManager.GetString("PD_ExportActions_vhcol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instead of keeping all version history in a single column, you can export each version in the history to its own row. These versions will appear underneath the data item row, in descending sort order, and in this case you&apos;ll need a separate CSV column to denote the version number of each history record. You &lt;b&gt;need&lt;/b&gt; to enter this CSV column name (for example &apos;Version&apos;) above this check-box option if ticked.&lt;br/&gt;&lt;br/&gt;Not applicable to &lt;a target=&quot;_blank&quot; href=&quot;http://SharePoint-Tools.net/PeopleZen/&quot;&gt;User P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PD_ExportActions_vhrows {
            get {
                return ResourceManager.GetString("PD_ExportActions_vhrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If ticked, this export action only ever exports items included in the currently displayed List View, applying the View-defined default sort orders and filters (but &lt;b&gt;not&lt;/b&gt; currently user-applied live sort order, filters or paging); otherwise, all List items are exported, unfiltered and in their original sort order.&lt;br/&gt;&lt;br/&gt;Not applicable to &lt;a target=&quot;_blank&quot; href=&quot;http://SharePoint-Tools.net/PeopleZen/&quot;&gt;User Profile exports via PeopleZen&lt;/a&gt;..
        /// </summary>
        public static string PD_ExportActions_view {
            get {
                return ResourceManager.GetString("PD_ExportActions_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name,title,cols,loc,enc,bom.
        /// </summary>
        public static string PL_ExportActions_0 {
            get {
                return ResourceManager.GetString("PL_ExportActions_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vhcol,vhrows,view,nopg,notb.
        /// </summary>
        public static string PL_ExportActions_4 {
            get {
                return ResourceManager.GetString("PL_ExportActions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item and Integration.
        /// </summary>
        public static string PT_ExportActions_a {
            get {
                return ResourceManager.GetString("PT_ExportActions_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Layout and Export Contents.
        /// </summary>
        public static string PT_ExportActions_c {
            get {
                return ResourceManager.GetString("PT_ExportActions_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting Options.
        /// </summary>
        public static string PT_ExportActions_f {
            get {
                return ResourceManager.GetString("PT_ExportActions_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string Tool_ExportActions_DefTitle {
            get {
                return ResourceManager.GetString("Tool_ExportActions_DefTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tool to define your ExportZen List data exports. Each export action specifies which columns to export and lets you customize various export-related options..
        /// </summary>
        public static string Tool_ExportActions_Desc {
            get {
                return ResourceManager.GetString("Tool_ExportActions_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_layouts/images/delcell.gif.
        /// </summary>
        public static string Tool_ExportActions_Icon {
            get {
                return ResourceManager.GetString("Tool_ExportActions_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Actions.
        /// </summary>
        public static string Tool_ExportActions_Title {
            get {
                return ResourceManager.GetString("Tool_ExportActions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Action.
        /// </summary>
        public static string Tool_ExportActions_TitleSingular {
            get {
                return ResourceManager.GetString("Tool_ExportActions_TitleSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and &lt;i&gt;Export Actions&lt;/i&gt;.
        /// </summary>
        public static string Tool_Transfer_Export_Extra {
            get {
                return ResourceManager.GetString("Tool_Transfer_Export_Extra", resourceCulture);
            }
        }
    }
}
